apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: ${APP_IMAGE}
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:${MONGO_PASSWORD}@mongodb.demo.svc.cluster.local:27017"

