apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-app
  namespace: pf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-app
  template:
    metadata:
      labels:
        app: pf-app
    spec:
      containers:
        - name: pf-app
          image: 228749873271.dkr.ecr.ap-south-1.amazonaws.com/develeap/pf-project:d1d68b093192bd89f0fbff1eb4effb23a5b6a947:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb.demo.svc.cluster.local:27017"

